guild_id: 1162017936656044042 # Regenerative Ag Coop

# A config entry per channel that should have disappearing messages enabled
channel_config_by_channel_id: 
  # test channel
  1333528605359214663:
    delay_unit: SECONDS
    delay_count: 5

enable_config:
  template: "Disappearing messages are enabled. Messages will be deleted after TIME_PERIOD."
  time_period_config:
    template: "COUNT UNIT"
    unit_config:
      SECONDS:
        singular: second
        plural: seconds
      MINUTES:
        singular: minute
        plural: minutes
      HOURS:
        singular: hour
        plural: hours
      DAYS:
        singular: day
        plural: days