########################################################################################################################
# This is the real configuration file used for the regenerative agriculture discord server.
#
# You can copy this config and edit it to create your own configuration file for your server.
#
# Every time you edit your config, you should restart the gatekeeper bot application so the new config gets read.
########################################################################################################################



# Your discord server id
guildId: 1162017936656044042 # Regenerative Agriculture



# All the member ids that should not be granted membership roles.
#
#   Not all members should be granted roles when they post.
#
#   For example, you may not want to give your bot a role when it posts.
excludedUserIds:
  - 1333526166015053844 # Compostinator
  - 1282462880532402206 # Gatekeeper Bot
  - 1348858373222825996 # Regen Yoda
  - 204255221017214977  # YAGPDB.xyz



# The rules for how users are granted membership roles in your server...
#
#   This is an ordered list.
#     - Roles at the top of this list have the lowest priority.
#     - If you define your rules such that a user can qualify for multiple roles at once, only the role with the highest priority (lowest in this list) will be granted to the user.
#     - When a role with a greater priority (lower in this list) is granted to a member, a "welcome message" is posted to a room.
#     - When a member is transitioned to a membership role with a lower priority, a "downgrade message" is posted to a
#     room.
#
#   There may be multiple ways a user can be granted a given role (aka paths). Each path to a role is defined through rules that you define.
#
# The null ruleId corresponds to a user without any membership roles.
roleConfigs:

# TODO
#
# - Visitor becomes Member if thumbs-up rules
#   + Automated message
# - Member becomes Inactive Member if no reactions or posts in 30 days
# - Inactive Member becomes Member if react in quiet-garden
#   + Automated message

  # Inactive Member
  - roleId: 1322321901586087976
    paths: []
      # # The user is a Member, and has made no posts or reactions in the last 30 days
      # - daysToConsider: 30
      #   rule:
      #     type: and
      #     rules:
      #       - type: has_role
      #         roleId: 1223026651340996698 # Member
      #       - type: no_posts_or_reactions


  # Visitor (no role)
  # Note: You _must_ have a config defined with roleId=null. This is the config that will be used for users that have no membership roles (e.g. just joined your server).
  - roleId: null
    paths: []

  # Member
  - roleId: 1223026651340996698
    paths:
      # A Visitor reacts to the message in #rules
      - daysToConsider: 0 # no post or reaction history used, only current state
        rule:
          type: and
          rules:
            - type: has_role
              roleId: null # Visitor
            - type: reacted
              emoji: "👍"
              messageId: 1552509864629108887 # message in rules
        welcomeMessageConfig:
          channel: 1552316869116035223 # hello
          template: "Welcome, USER_MENTION :wave:"
      # The user has the "Inactive Member" role, and reacts with a 👍 in #quiet-garden
      - daysToConsider: 0 # no post or reaction history used, only current state
        rule:
          type: and
          rules:
            - type: has_role
              roleId: 1322321901586087976 # Inactive Member
            - type: reacted
              emoji: "👍"
              messageId: 1322322546296885341 # message in quiet garden
        welcomeMessageConfig:
          channel: 1552316869116035223 # hello
          template: "Welcome back, USER_MENTION!"


# The name to log when a user qualifies for no roles, and/or the roleConfig with roleId=null
noRoleName: "Visitor"



# Post this message when a member transitions to a membership role with a lower priority order than the role they had.
downgradeMessageConfig:
  channel: 1230667079213125702 # moderation-log
  template: "USERNAME has transitioned from PREVIOUS_ROLE to CURRENT_ROLE."



# The channel to log user activity in (e.g. posts & reactions)
persistenceConfig:
  channel: 1279607063646965921 # persistence-log

# The channel to record uncaught top level errors in
errorConfig:
  channel: 1230667079213125702 # moderation-log

# Slash commands to register for this bot.
# Discord displays these commands with a leading `/`.
slashCommandConfig:
  postCommand: "rac-post"
  editCommand: "rac-edit"

welcomeToGuildMessageConfig:
  null
