########################################################################################################################
# This is the real configuration file used for the regenerative agriculture discord server.
#
# You can copy this config and edit it to create your own configuration file for your server.
#
# Every time you edit your config, you should restart the gatekeeper bot application so the new config gets read.
########################################################################################################################



# Your discord server id
guildId: 1162017936656044042 # Regenerative Agriculture



# All the member ids that should not be granted membership roles.
#
#   Not all members should be granted roles when they post.
#
#   For example, you may not want to give your bot a role when it posts.
excludedUserIds:
  - 1333526166015053844 # Compostinator
  - 1282462880532402206 # Gatekeeper Bot
  - 204255221017214977  # YAGPDB.xyz



# The rules for how users are granted membership roles in your server...
#
#   This is an ordered list.
#     - Roles at the top of this list have the lowest priority.
#     - If you define your rules such that a user can qualify for multiple roles at once, only the role with the highest priority (lowest in this list) will be granted to the user.
#     - When a role with a greater priority (lower in this list) is granted to a member, a "welcome message" is posted to a room.
#     - When a member is transitioned to a membership role with a lower priority, a "downgrade message" is posted to a
#     room.
#
#   There may be multiple ways a user can be granted a given role (aka paths). Each path to a role is defined through rules that you define.
#
# The null ruleId corresponds to a user without any membership roles.
roleConfigs:

  # Inactive
  - roleId: 1322321679006961664
    paths:
      # The user is a Visitor, has made no posts or reactions in the last 7 days, and they joined some time before 7 days ago
      - daysToConsider: 7
        rule:
          type: and
          rules:
            - type: has_role
              roleId: null # Visitor
            - type: no_posts_or_reactions
            - type: joined_before
      # The user is a Guest, and has made no posts or reactions in the last 14 days
      - daysToConsider: 14
        rule:
          type: and
          rules:
            - type: has_role
              roleId: 1240396803946582056 # Guest
            - type: no_posts_or_reactions
      # The user is an Inactive Member, and has made no posts or reactions in the last 365 days
      - daysToConsider: 365
        rule:
          type: and
          rules:
            - type: has_role
              roleId: 1322321901586087976 # Inactive Member
            - type: no_posts_or_reactions

  # Inactive Member
  - roleId: 1322321901586087976
    paths:
      # The user is an Active Member, and has made no posts or reactions in the last 14 days
      - daysToConsider: 14
        rule:
          type: and
          rules:
            - type: has_role
              roleId: 1223026651340996698 # Active Member
            - type: no_posts_or_reactions

  # Visitor (no role)
  # Note: You _must_ have a config defined with roleId=null. This is the config that will be used for users that have no membership roles.
  - roleId: null
    paths:
      # The user has the "Inactive" role, and reacts with a 👍 in #quiet-garden
      - daysToConsider: 0 # no post or reaction history used, only current state
        rule:
          type: and
          rules:
            - type: has_role
              roleId: 1322321679006961664 # Inactive
            - type: reacted
              emoji: "👍"
              messageId: 1322322546296885341 # message in quiet garden
        welcomeMessageConfig:
          channel: 1162019178513956954 # introductions
          template: "Welcome back, USER_MENTION!"

  # Guest
  - roleId: 1240396803946582056
    paths:
      # The user is a Visitor, and has at least 1 post in the last 14 days
      - daysToConsider: 14
        rule:
          type: and
          rules:
            - type: has_role
              roleId: null # no active role, aka visitor
            - type: post_days
              atLeast: 1
        welcomeMessageConfig:
          channel: 1162017937796911209 # connect
          template: "A warm hello to our newest Guest, USER_MENTION :relaxed:"
      # The user has the "Inactive" role, has posted within the last 180 days, and reacts with a 👍 in #quiet-garden
      - daysToConsider: 180
        rule:
          type: and
          rules:
            - type: has_role
              roleId: 1322321679006961664 # Inactive
            - type: post_days
              atLeast: 1
            - type: reacted
              emoji: "👍"
              messageId: 1322322546296885341 # message in quiet garden
        welcomeMessageConfig:
          channel: 1162017937796911209 # connect
          template: "Welcome back, USER_MENTION!"

  # Active Member
  - roleId: 1223026651340996698
    paths:
      # The user is a Guest, and has made at least 4 posts in the last 60 days
      - daysToConsider: 60
        rule:
          type: and
          rules:
            - type: has_role
              roleId: 1240396803946582056 # Guest
            - type: post_days
              atLeast: 4
        welcomeMessageConfig:
          channel: 1223262623194153111 # community
          template: >-
            Welcome to our community of practice, USER_MENTION! :farmer:
            
            
            You are now an Active Member :relieved: You can choose your name-tag color in <#1228353194493476894>.
            
            
            When you have a few minutes of free time, please take a brief glance over our [Community Guide](https://regenagcoop.org/community-guide/).
      # The user has the "Inactive Member" role, and reacts with a 👍 in #quiet-garden
      - daysToConsider: 0 # no post or reaction history used, only current state
        rule:
          type: and
          rules:
            - type: has_role
              roleId: 1322321901586087976 # Inactive Member
            - type: reacted
              emoji: "👍"
              messageId: 1322322546296885341 # message in quiet garden
        welcomeMessageConfig:
          channel: 1223262623194153111 # community
          template: "Welcome back, USER_MENTION :relaxed:"



# The name to log when a user qualifies for no roles, and/or the roleConfig with roleId=null
noRoleName: "Visitor"



# Post this message when a member transitions to a membership role with a lower priority order than the role they had.
downgradeMessageConfig:
  channel: 1230667079213125702 # moderation-log
  template: "USERNAME has transitioned from PREVIOUS_ROLE to CURRENT_ROLE."



# The channel to log user activity in (e.g. posts & reactions)
persistenceConfig:
  channel: 1279607063646965921


# TODO #26: make optional
welcomeToGuildMessageConfig:
  channel: 1162019178513956954 # introductions
  template: >-
    Welcome, USER_MENTION! To kick things off, we'd love to hear a little about your interests and experiences in regeneration. We sent you a direct message with some questions you can use to inspire your introduction.

  directMessageConfig:
    message: >-
      Welcome to the Regenerative Ag Coop!
      
      
      Here are some questions we'd like to connect with you on. These are just suggestions, feel free to introduce yourself in whatever way is comfortable :relieved:
      
      
      When you're ready, please come introduce yourself over in <#1162019178513956954>.
      
      
      
      1. **Tell us a bit about your journey into regenerative agriculture.** 
         Where are you located (roughly)? What inspired you to pursue regenerative practices? How long have you been working in this space? 
      
      2. **What does your regenerative operation look like?** 
         We'd love to hear details about your farm, business, or project—its size, focus (e.g., livestock, crops, agroforestry), and any key practices you’re using.
      
      3. **What is the biggest challenge you’re currently facing in your work?** 
         Are there particular obstacles—such as access to markets, managing soil health, or regulatory hurdles—that you'd like support or advice on?
      
      4. **What skills, knowledge, or experiences can you offer to other members?** 
         Maybe you have expertise in composting, marketing local produce, or navigating grants... How would you like to contribute?
      
      5. **What are you most excited to explore with our community?** 
         Are there specific topics or collaborations you’re hoping to engage with? E.g. biodiversity, carbon markets, creating resilient local food systems...
